sudo: required
sevices:
    - docker

before_install:
    - docker build -t ubaid496/docker-react -f Dockerfile.dev .

script:
    - docker run ubaid496/docker-react npm run test -- --coverage
         
